name: Deploy Quarkus Lambda (Java 21) - QA

on:
  push:
    branches: [qa, feature/*]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      LAMBDA_FUNCTION_NAME: kata-convertercode-mngr

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: "21"
          cache: maven

      - name: Build Lambda zip (Quarkus)
        run: |
          mvn -q clean package
          test -f target/function.zip

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name "$LAMBDA_FUNCTION_NAME" \
            --zip-file fileb://target/function.zip

      - name: Wait until function updated
        run: |
          aws lambda wait function-updated \
            --function-name "$LAMBDA_FUNCTION_NAME"

      - name: Show deployed version info
        run: |
          aws lambda get-function-configuration \
            --function-name "$LAMBDA_FUNCTION_NAME" \
            --query '{FunctionName:FunctionName,Runtime:Runtime,Handler:Handler,LastModified:LastModified,CodeSize:CodeSize}' \
            --output table
